echo $MODEL_FILE_NAME

touch $MODEL_FILE_NAME
echo "FROM" $MODEL_NAME >> $MODEL_FILE_NAME
echo "PARAMETER temperature" $MODEL_TEMP >> $MODEL_FILE_NAME
echo "PARAMETER num_ctx" $MODEL_CONTEXT_LEN >> $MODEL_FILE_NAME
echo "SYSTEM" $MODEL_SYSTEM_PROMPT >> $MODEL_FILE_NAME